version: '3.2'

services:
  devcontainer:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
    container_name: phishield-devcontainer
    env_file: .env
    image: phishield/devcontainer:latest
    working_dir: /phishield
    tty: true
    user: vscode:vscode
    shm_size: "4gb"
    volumes:
      - ./:/phishield/
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/vscode/.ssh
    depends_on:
      - database

  backend:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    working_dir: /phishield/backend/phishield
    tty: true
    user: vscode:vscode
    command: hatch --no-interactive -v run phishield api --dev
    restart: on-failure:3
    pid: service:devcontainer
    network_mode: service:devcontainer
    volumes_from:
      - devcontainer
    depends_on:
      - database
      - storage
      - cache
  
  worker:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    working_dir: /phishield/backend/phishield
    tty: true
    user: vscode:vscode
    command: hatch --no-interactive -v run phishield worker --dev
    restart: on-failure:3
    pid: service:devcontainer
    network_mode: service:devcontainer
    volumes_from:
      - devcontainer
    depends_on:
      - database
      - storage
      - cache

  database:
    image: bitnami/postgresql:latest
    container_name: phishield-database
    env_file: .env
  
  cache:
    image: redis:6-alpine
    restart: always
  
  storage:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env