version: '3.2'

services:
  backend:
    image: kfbfarley/phishield:v0.0.1
    container_name: phishield-backend
    command: api
    env_file: .env
    depends_on:
      - cache

  cache:
    image: redis:6-alpine
    container_name: phishield-cache
    restart: always

  nginx:
    image: bitnami/nginx:latest
    container_name: phishield-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - phishield-volume-nginx:/opt/bitnami/nginx/conf/server_blocks:rw
      - phishield-volume-letsencrypt:/etc/letsencrypt:rw

  certbot:
    image: certbot/dns-cloudflare
    container_name: phishield-certbot
    volumes:
      - phishield-volume-letsencrypt:/etc/letsencrypt:rw
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --register-unsafely-without-email
      --agree-tos --no-eff-email
      --force-renewal
      -d '*.phishield.dev'

volumes:
  phishield-volume-letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/docker/etc/letsencrypt
  phishield-volume-nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/docker/etc/nginx

networks:
  phishield-network:
    driver: bridge